<?php
/**
 * Created by PhpStorm.
 * User: ggrenuy
 * Date: 27.05.15
 * Time: 14:00
 */
function round1_exam_menu() {
  $items['round1_exam/page_1'] = array(
    'title' => 'hook-theme',
    'page callback' => 'round1_exam_cloobeck',
    'access callback' => true
  );
  return $items;
}
function round1_exam_cloobeck(){
  return theme("round1_exam_content", array("text"=>"привет мир")).theme("round1_exam_content_tpl", array("text"=>"Второй привет мир шаблон с файла"));
}


function round1_exam_theme(){
  return array(
    'round1_exam_content' => array(
      'variables' => array('text' => NULL),
    ),
    'round1_exam_content_tpl' => array(
      'varables' => array('text' => NULL),
      'template' => "round1_exam_tpl",
      'path' => drupal_get_path('module', 'round1_exam')."/",
    )
  );
}

function theme_round1_exam_content($variables){
  return "<strong>".$variables['text']."</strong>";
}

//hook_theme