<?php
/**
 * Created by PhpStorm.
 * User: ggrenuy
 * Date: 10.05.15
 * Time: 17:33
 */

function round0_menu() {
    $items['round0/example-hook-menu'] = array(
        'title' => 'example hook menu',
        'page callback' => 'round0_example_hook_menu',
        'access callback' => true,
      'weight' => 100,
    );
    $items['round0/example-form'] = [
        'title' => 'Example form',
        'page callback' => 'round0_example_get_form',
        'access callback' => true,
      'weight' => 100,
    ];
    return $items;
}

/**
 * @return string
 */
function round0_example_hook_menu(){
    return "Это пример хук меню";
}

/**
 * @param $form
 * @param $form_state
 * @return mixed
 */
function round0_form_search_block_form_alter(&$form, &$form_state){
    $form['resetbutton'] = array(
        '#markup' => '<button type="reset">'.t("Reset").'</button>',
        '#weight' => 1000,
    );
    return $form;
}

function round0_example_get_form(){
    return drupal_get_form('round0_example_form');
}

/**
 * @param $form
 * @param $form_state
 * @return array|mixed
 */
function round0_example_form($form, &$form_state){
    // Display page 2 if $form_state['page_num'] == 2
    if (!empty($form_state['page_num']) && $form_state['page_num'] == 2) {
        return round0_example_form_two($form, $form_state);
    }
    $form_state['page_num'] = 1;

    $form['description'] = array(
        '#type' => 'item',
        '#title' => t('Example api form'),
    );
    $form['name'] = array(
        '#type' => 'textfield',
        '#title' => t('Name'),
        '#default_value' => !empty($form_state['values']['name']) ? $form_state['values']['name'] : '',
    );
    $form['submit'] = array(
        '#type' => 'submit',
        '#title' => t('Name'),
        '#value' => t('Two step'),
        '#submit' => array('round0_example_form_next_submit'),
    );
    return $form;

}

function round0_example_form_two($form, &$form_state){
  $form['secondname'] = array(
    '#type' => 'textfield',
    '#title' => t('Secondname'),
  );
  $form['#tree'] = TRUE;

  //Name girlfriend
  $form['girlfriend']['description'] = array(
    '#type' => 'item',
    '#title' => t('Send name girlfriend'),
  );

  if (empty($form_state['num_names'])) {
    $form_state['num_names'] = 1;
  }

  for ($i = 1; $i <= $form_state['num_names']; $i++) {
    $form['girlfriend']['name'][$i] = array(
      '#type' => 'fieldset',
      '#title' => t('Name #@num', array('@num' => $i)),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
    );

    $form['girlfriend']['name'][$i]['name'] = array(
      '#type' => 'textfield',
      '#title' => t('Name girlfriend'),
      '#description' => t("Name girlfriend"),
      '#size' => 20,
      '#maxlength' => 20,
      '#required' => TRUE,
    );
  }

  // Adds "Add another name" button.
  $form['add_name'] = array(
    '#type' => 'submit',
    '#value' => t('Add new girl'),
    '#submit' => array('round0_example_form_two_add_name_girlfrfriend'),
  );
  if ($form_state['num_names'] > 1) {
    $form['remove_name'] = array(
      '#type' => 'submit',
      '#value' => t('Remove last girl'),
      '#submit' => array('round0_example_form_two_remove_name_girlfrfriend'),
      // Since we are removing a name, don't validate until later.
      '#limit_validation_errors' => array(),
    );
  }

  $form['back'] = array(
    '#type' => 'submit',
    '#title' => t('Name'),
    '#value' => t('Back step'),
    '#submit' => array('round0_example_form_two_back'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#title' => t('Name'),
    '#value' => t('Finish'),
    '#submit' => array('round0_example_form_two_submit'),
  );

  return $form;
}

function round0_example_form_two_remove_name_girlfrfriend($form, &$form_state){
  if ($form_state['num_names'] > 1) {
    $form_state['num_names']--;
  }
  $form_state['rebuild'] = TRUE;
}

function round0_example_form_two_add_name_girlfrfriend($form, &$form_state) {
  $form_state['num_names']++;
  $form_state['rebuild'] = TRUE;
}

function round0_example_form_two_submit($form, &$form_state){
  $form_state['page_values'][2] = &$form_state['values'];

  drupal_set_message(t('name="@name", secondname="@secondname" name girlfriend="@girlfriend"',
    array(
      '@name' => $form_state['page_values'][1]['name'],
      '@secondname' => $form_state['page_values'][2]['secondname'],
      '@girlfriend' => print_r($form_state['page_values'][2]['girlfriend']['name'],true),
    )
  ));
}

function round0_example_form_two_back($form, &$form_state) {
  $form_state['page_values'][2] = $form_state['values'];
  $form_state['values'] = $form_state['page_values'][1];
  $form_state['page_num'] = 1;
  $form_state['rebuild'] = TRUE;
}

function round0_example_form_next_submit($form, &$form_state){

  // Values are saved for each page.
  // to carry forward to subsequent pages in the form.
  // and we tell FAPI to rebuild the form.
  $form_state['page_values'][1] = &$form_state['values'];

  if (!empty($form_state['page_values'][2])) {
    $form_state['values'] = $form_state['page_values'][2];
  }

  // When form rebuilds, it will look at this to figure which page to build.
  $form_state['page_num'] = 2;
  $form_state['rebuild'] = TRUE;
}

function round0_block_info() {

    $blocks['example_header_1'] = array(
        'info' => t('Example round0'),
        'status' => TRUE,
        'region' => 'header',
        //'visibility' => BLOCK_VISIBILITY_LISTED,
        //'pages' => 'node/*',
    );

    return $blocks;
}

function round0_block_view($delta = '') {
    $block['subject'] = t('Пример титле для блока');
    $block['content'] = round0_block_contents('example_header_1');
    return $block;
}

function round0_block_contents($block_id){
    $result = array(
        '#markup' => variable_get($block_id,
            t('A default value. This block was created at %time',
                array('%time' => date('c'))
            )
        ),
    );
    return $result;

}
/**
 * @param $data
 * @param $block
 */
function round0_block_view_round0_example_header_1_alter(&$data, $block) {

    $data['subject'] = t('New title of the block');
}
function round0_block_configure($delta = ''){
    $form['example_header_1'] = array(
        '#type' => 'textfield',
        '#title' => t('Block contents'),
        '#size' => 60,
        '#description' => t('This text will appear in the example block.'),
        '#default_value' => variable_get('block_example_string', t('Some example content.')),
    );

    return $form;

}

function round0_block_save($delta = '', $edit = array()) {
    // We need to save settings from the configuration form.
    // We need to check $delta to make sure we are saving the right block.
    if ($delta == 'example_header_1') {
        // Have Drupal save the string to the database.
        variable_set('block_example_string', $edit['example_header_1']);
    }
}